name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Define reusable workflow to avoid duplication
jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.get-flutter-version.outputs.version }}
    steps:
      - id: get-flutter-version
        run: echo "version=$(curl -s https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json | jq -r '.releases[] | select(.channel == "stable") | .version' | head -n 1)" >> $GITHUB_OUTPUT

  build-macos:
    needs: setup-flutter
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-flutter.outputs.flutter-version }}
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build macOS app
        run: flutter build macos --release
      
      - name: List build directory contents
        run: find build/macos -type d -name "*.app"
      
      - name: Archive macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/markdown_editor.app
          if-no-files-found: warn
  
  build-windows:
    needs: setup-flutter
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-flutter.outputs.flutter-version }}
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      
      - name: Build Windows app
        run: flutter build windows --release
      
      - name: List build directory contents
        run: dir build\windows\x64\Release /s
        shell: cmd
      
      - name: Archive Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/Release
          if-no-files-found: warn
  
  build-linux:
    needs: setup-flutter
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libblkid-dev liblzma-dev libsecret-1-dev libjsoncpp-dev libsqlite3-dev libfontconfig1-dev libxkbcommon-dev ninja-build
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-flutter.outputs.flutter-version }}
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop
      
      - name: Build Linux app
        run: flutter build linux --release
      
      - name: List build directory contents
        run: find build/linux -type d
      
      - name: Archive Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle
          if-no-files-found: warn
