name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

# Define reusable workflow to avoid duplication
jobs:
  setup-flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.get-flutter-version.outputs.version }}
    steps:
      - id: get-flutter-version
        run: echo "version=$(curl -s https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json | jq -r '.releases[] | select(.channel == "stable") | .version' | head -n 1)" >> $GITHUB_OUTPUT

  build-macos:
    needs: setup-flutter
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-flutter.outputs.flutter-version }}
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build macOS app
        run: flutter build macos --release
      
      - name: List build directory contents
        run: find build/macos -type d -name "*.app"
      
      - name: Archive macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/markdown_editor.app
          if-no-files-found: warn
  
  build-windows:
    needs: setup-flutter
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-flutter.outputs.flutter-version }}
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      
      - name: Build Windows app
        run: flutter build windows --release
      
      - name: List build directory structure
        run: dir build\windows /s
        shell: cmd
      
      - name: Archive Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release
          if-no-files-found: warn
  
  build-linux:
    needs: setup-flutter
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libblkid-dev liblzma-dev libsecret-1-dev libjsoncpp-dev libsqlite3-dev libfontconfig1-dev libxkbcommon-dev ninja-build
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup-flutter.outputs.flutter-version }}
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop
      
      - name: Build Linux app
        run: flutter build linux --release
      
      - name: List build directory contents
        run: find build/linux -type d
      
      - name: Archive Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle
          if-no-files-found: warn

  # Create GitHub Release when a tag is pushed
  create-release:
    needs: [build-macos, build-windows, build-linux]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Get tag message for changelog
          TAG_MESSAGE=$(git tag -l --format='%(contents)' "${GITHUB_REF#refs/tags/}")
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          # Package macOS app - preserve app bundle structure
          if [ -d "artifacts/macos-build" ]; then
            # Create a temporary directory to hold the app
            mkdir -p temp_macos
            # Copy the app bundle to the temp directory, preserving the structure
            cp -R artifacts/macos-build/markdown_editor.app temp_macos/
            # Create the zip from outside the app directory to preserve the .app structure
            cd temp_macos
            zip -r ../release-assets/markdown_editor-mac-${{ steps.get_version.outputs.VERSION }}.zip .
            cd ..
            # Clean up
            rm -rf temp_macos
          fi
          # Package Windows app - create a clean structure
          if [ -d "artifacts/windows-build" ]; then
            mkdir -p temp_windows/markdown_editor
            cp -R artifacts/windows-build/* temp_windows/markdown_editor/
            # Create a simple README file
            echo "Markdown Editor for Windows" > temp_windows/README.txt
            echo "Version ${{ steps.get_version.outputs.VERSION }}" >> temp_windows/README.txt
            echo "\nTo run the application, open the markdown_editor folder and run markdown_editor.exe" >> temp_windows/README.txt
            cd temp_windows
            zip -r ../release-assets/markdown_editor-windows-${{ steps.get_version.outputs.VERSION }}.zip .
            cd ..
            rm -rf temp_windows
          fi
          # Package Linux app - create a clean structure
          if [ -d "artifacts/linux-build" ]; then
            mkdir -p temp_linux/markdown_editor
            cp -R artifacts/linux-build/* temp_linux/markdown_editor/
            # Create a simple README file
            echo "Markdown Editor for Linux" > temp_linux/README.txt
            echo "Version ${{ steps.get_version.outputs.VERSION }}" >> temp_linux/README.txt
            echo "\nTo run the application:" >> temp_linux/README.txt
            echo "1. Open a terminal in the markdown_editor directory" >> temp_linux/README.txt
            echo "2. Run ./markdown_editor" >> temp_linux/README.txt
            cd temp_linux
            tar -czvf ../release-assets/markdown_editor-linux-${{ steps.get_version.outputs.VERSION }}.tar.gz .
            cd ..
            rm -rf temp_linux
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Markdown Editor v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          files: release-assets/*
          draft: false
          prerelease: false
